title: 
author: Shinjiro Sakaitani

lang: ja
timezone: Asia/Tokyo

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docker-compose.yml
  - vendor/

theme: minima

github_username: shin2ro
twitter_username: shin2ro_o

