title: 
author: Shinjiro Sakaitani
lang: ja
timezone: Asia/Tokyo

github_username: shin2ro
twitter_username: shin2ro_o

markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docker-compose.yml
  - vendor/
